service: etl-covid19

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
frameworkVersion: '2'

provider:
  name: aws
  runtime: python3.7

# you can overwrite defaults here
  stage: dev
  region: us-east-1
  profile: joseangel1196

layers:
  ETL:
    path: layers
    name: ${self:service}
    description: Event-Driven Python on AWS
    compatibleRuntimes:
      - python3.6
      - python3.7
      - python3.8

functions:
  main:
    handler: handler.app

#    Define function environment variables here
   environment:
     NYC_TIMES_URL: https://raw.githubusercontent.com/nytimes/covid-19-data/master/us.csv
     JOHNS_HOPKINS_URL: https://raw.githubusercontent.com/datasets/covid-19/master/data/time-series-19-covid-combined.csv
     DATABASE: ${ssm:/database/covid19/database~true}
     USER: ${ssm:/database/covid19/user~true}
     PASSWORD: ${ssm:/database/covid19/password~true}
     HOST: ${ssm:/database/covid19/endpoint~true}
     TABLE: records
     TEMPORARY_TABLE: tmp

package:
  exclude:
    - terraform/**
    - README.md
  individually: true

resources:
 Resources:
   NotifySNS:
     Type: AWS::SNS::Topic
     Properties:
       TopicName: Notify_etl_covid19
       Subscription:
        - Endpoint: "joseangel1196@hotmail.com"
          Protocol: email
